version: '1'
services:
  microservicio:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:oracle:thin:@k8otoik423mjwkax_tp?TNS_ADMIN=/app/oracle_wallet/
      - spring.datasource.username=usuariofs3
      - spring.datasource.password=ClaveFullStack3
    restart: always